const SUPABASE_URL="https://nrmglwgrwglgkrhkohby.supabase.co";
const SUPABASE_KEY="sb_publishable_v3WJh6ElDsVW0cBfBWsSqA_Q1lXpnjn";
const WPP="5547984276419";
let servicos=[], adicionais=[], horariosDB=[], agendamentos=[], horaSel="", servicoAtual=null, extrasSel=[], valorTotal=0, tempoTotal=0;
let loginData=JSON.parse(localStorage.getItem("studio_sabrina_login")||'{"user":"admin","pass":"0000"}');
async function api(path,opt={}){const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...opt,headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json",Prefer:"return=representation",...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;return await r.json()}
async function edgeFunction(name,payload){const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"Erro ao executar função.");return d}
function money(v){return Number(v||0).toFixed(2).replace(".",",")}function tempo(m){m=Number(m||0);let h=Math.floor(m/60),r=m%60;return h&&r?`${h}h${r}min`:h?`${h}h`:`${r}min`}
function tela(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");fechar();if(id==="internal")carregarAgenda()}
function abrirMenu(){drawer.classList.toggle("open");overlay.classList.toggle("show")}function fechar(){drawer.classList.remove("open");overlay.classList.remove("show")}
async function carregar(){try{servicos=await api("servicos?select=*&ativo=eq.true&order=nome.asc");adicionais=await api("adicionais?select=*&ativo=eq.true&order=nome.asc");horariosDB=await api("horarios?select=*&ativo=eq.true&order=dia_semana.asc,horario.asc");await carregarAgenda();renderCliente();renderInterno()}catch(e){alert("Erro ao carregar Supabase: "+e.message)}}
async function carregarAgenda(){try{agendamentos=await api("agendamentos?select=*,clientes(nome,telefone,email)&order=created_at.desc");renderAgenda()}catch(e){console.warn(e.message)}}
function renderCliente(){servico.innerHTML='<option value="">Selecione</option>'+servicos.map(s=>`<option value="${s.id}">${s.nome} — R$${money(s.valor)} — ${tempo(s.tempo_minutos)}</option>`).join("");extras.innerHTML="";adicionais.forEach(a=>{let d=document.createElement("div");d.className="extra";d.innerHTML=`<div><strong>${a.nome}</strong><p class="muted">${a.descricao||""}</p></div><div><strong>R$${money(a.valor)}</strong><br><small>+${a.tempo_minutos}min</small></div><input type="checkbox" class="extraCheck" value="${a.id}">`;extras.appendChild(d)});document.querySelectorAll(".extraCheck").forEach(c=>c.onchange=calcular);let box=document.getElementById("horarios"),usados=new Set();box.innerHTML="";horariosDB.forEach(h=>{let hr=String(h.horario).slice(0,5);if(usados.has(hr))return;usados.add(hr);let b=document.createElement("button");b.className="hour";b.textContent=hr;b.onclick=()=>{document.querySelectorAll(".hour").forEach(x=>x.classList.remove("active"));b.classList.add("active");horaSel=hr};box.appendChild(b)});calcular()}
function calcular(){servicoAtual=servicos.find(s=>s.id===servico.value)||null;valorTotal=servicoAtual?Number(servicoAtual.valor):0;tempoTotal=servicoAtual?Number(servicoAtual.tempo_minutos):0;extrasSel=[];document.querySelectorAll(".extraCheck").forEach(c=>{if(c.checked){let a=adicionais.find(x=>x.id===c.value);if(a){extrasSel.push(a);valorTotal+=Number(a.valor);tempoTotal+=Number(a.tempo_minutos)}}});summary.innerHTML=`Valor total: R$${money(valorTotal)}<br>Tempo estimado: ${tempo(tempoTotal)}`}
async function confirmarAgendamento(){if(!nome.value||!nascimento.value||!telefone.value||!email.value)return alert("Preencha o cadastro.");if(!servicoAtual)return alert("Escolha um serviço.");if(!data.value)return alert("Escolha a data.");if(!horaSel)return alert("Escolha um horário.");try{await edgeFunction("criar-agendamento",{cliente:{nome:nome.value.trim(),nascimento:nascimento.value,telefone:telefone.value.trim(),email:email.value.trim()},agendamento:{servico_id:servicoAtual.id,data_agendamento:data.value,horario:horaSel,adicionais_ids:extrasSel.map(e=>e.id)}});ok.style.display="block";ok.innerHTML="Agendamento solicitado com sucesso!<br>O Studio recebeu a notificação automática no WhatsApp.";nome.value=nascimento.value=telefone.value=email.value=data.value="";horaSel="";document.querySelectorAll(".hour").forEach(b=>b.classList.remove("active"));await carregarAgenda();alert("Agendamento salvo e WhatsApp enviado.")}catch(e){alert("Erro ao salvar: "+e.message)}}
function logar(){if(user.value.trim()===loginData.user&&pass.value.trim()===loginData.pass){loginBox.style.display="none";dashboard.style.display="block";carregarAgenda()}else alert("Usuário ou senha incorretos.")}
function sair(){loginBox.style.display="block";dashboard.style.display="none"}
function renderAgenda(){qtd.textContent=agendamentos.length;previsto.textContent="R$"+agendamentos.reduce((s,a)=>s+Number(a.valor_total||0),0).toFixed(0);lista.innerHTML=agendamentos.length?"":"<p class='muted'>Nenhum agendamento encontrado.</p>";agendamentos.forEach(a=>{let c=a.clientes||{},s=servicos.find(x=>x.id===a.servico_id),d=document.createElement("div");d.className="item";d.innerHTML=`<strong>${c.nome||"Cliente"}</strong><br>Serviço: ${s?s.nome:"Serviço"}<br>Data: ${a.data_agendamento} às ${String(a.horario).slice(0,5)}<br>Tempo: ${tempo(a.tempo_total_minutos)}<br>Valor: R$${money(a.valor_total)}<br>WhatsApp: ${c.telefone||""}<br><span class="badge">${a.status}</span><div class="actions"><button class="btn success small">Confirmar</button><button class="btn danger small">Cancelar</button></div>`;d.querySelector(".success").onclick=()=>statusAgendamento(a.id,"confirmado");d.querySelector(".danger").onclick=()=>statusAgendamento(a.id,"cancelado");lista.appendChild(d)})}
async function statusAgendamento(id,status){await api("agendamentos?id=eq."+id,{method:"PATCH",body:JSON.stringify({status})});await carregarAgenda()}
function renderInterno(){renderServicos();renderExtras();configUser.value=loginData.user;configPass.value=loginData.pass}
function renderServicos(){listaServicos.innerHTML="";servicos.forEach(s=>{let d=document.createElement("div");d.className="item";d.innerHTML=`<strong>${s.nome}</strong><br>R$${money(s.valor)} • ${tempo(s.tempo_minutos)}<br><span class="muted">${s.descricao||""}</span><div class="actions"><button class="btn soft small">Editar</button><button class="btn danger small">Excluir</button></div>`;d.querySelector(".soft").onclick=()=>editarServico(s);d.querySelector(".danger").onclick=()=>desativar("servicos",s.id);listaServicos.appendChild(d)})}
async function salvarSrv(){if(!srvNome.value||!srvValor.value||!srvTempo.value)return alert("Preencha tudo.");await api("servicos",{method:"POST",body:JSON.stringify({nome:srvNome.value,valor:Number(srvValor.value),tempo_minutos:Number(srvTempo.value),descricao:srvDesc.value,ativo:true})});srvNome.value=srvValor.value=srvTempo.value=srvDesc.value="";await carregar()}
async function editarServico(s){let n=prompt("Nome",s.nome);if(n===null)return;let v=prompt("Valor",s.valor);if(v===null)return;let t=prompt("Tempo",s.tempo_minutos);if(t===null)return;let d=prompt("Descrição",s.descricao||"");if(d===null)return;await api("servicos?id=eq."+s.id,{method:"PATCH",body:JSON.stringify({nome:n,valor:Number(v),tempo_minutos:Number(t),descricao:d})});await carregar()}
function renderExtras(){listaExtras.innerHTML="";adicionais.forEach(a=>{let d=document.createElement("div");d.className="item";d.innerHTML=`<strong>${a.nome}</strong><br>R$${money(a.valor)} • +${a.tempo_minutos}min<br><span class="muted">${a.descricao||""}</span><div class="actions"><button class="btn soft small">Editar</button><button class="btn danger small">Excluir</button></div>`;d.querySelector(".soft").onclick=()=>editarExtra(a);d.querySelector(".danger").onclick=()=>desativar("adicionais",a.id);listaExtras.appendChild(d)})}
async function salvarAdd(){if(!addNome.value||!addValor.value||!addTempo.value)return alert("Preencha tudo.");await api("adicionais",{method:"POST",body:JSON.stringify({nome:addNome.value,valor:Number(addValor.value),tempo_minutos:Number(addTempo.value),descricao:addDesc.value,ativo:true})});addNome.value=addValor.value=addTempo.value=addDesc.value="";await carregar()}
async function editarExtra(a){let n=prompt("Nome",a.nome);if(n===null)return;let v=prompt("Valor",a.valor);if(v===null)return;let t=prompt("Tempo",a.tempo_minutos);if(t===null)return;let d=prompt("Descrição",a.descricao||"");if(d===null)return;await api("adicionais?id=eq."+a.id,{method:"PATCH",body:JSON.stringify({nome:n,valor:Number(v),tempo_minutos:Number(t),descricao:d})});await carregar()}
async function desativar(tabela,id){if(!confirm("Excluir/desativar?"))return;await api(tabela+"?id=eq."+id,{method:"PATCH",body:JSON.stringify({ativo:false})});await carregar()}
function salvarConfigLocal(){loginData={user:configUser.value||"admin",pass:configPass.value||"0000"};localStorage.setItem("studio_sabrina_login",JSON.stringify(loginData));alert("Salvo neste navegador.")}
function mudarTab(id){document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.querySelector(`[data-tab="${id}"]`).classList.add("active");document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active")}
function wpp(){window.open("https://wa.me/"+WPP,"_blank")}function maps(){window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent("R. Jailson Francisco de Miranda, 95, CEP 88341-173"),"_blank")}
menuBtn.onclick=abrirMenu;overlay.onclick=abrirMenu;wppMenu.onclick=wpp;mapsMenu.onclick=maps;mapsHome.onclick=maps;float.onclick=wpp;confirmar.onclick=confirmarAgendamento;login.onclick=logar;logout.onclick=sair;atualizar.onclick=carregarAgenda;salvarServico.onclick=salvarSrv;salvarExtra.onclick=salvarAdd;salvarConfig.onclick=salvarConfigLocal;servico.onchange=calcular;document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>tela(b.dataset.screen));document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>mudarTab(b.dataset.tab));carregar();
